"""Explanations for decisions, generated by the SAME frozen backbone (docs/roadmap_designs.md §4).

Separate from the decision path: /v1/decide never generates text; this module backs the opt-in /v1/explain.
  1. evidence  : leave-one-record-out occlusion (delete one JSON member / list item / text line, re-decide in one
                 batched call); a record's weight is the drop in P(chosen). Returned as character offsets.
  2. generation: greedy (or sampled) continuation of the backbone from the state, prompted with the decision, its
                 runner-up and the evidence records; the tied LM head gives the next-token logits.
  3. check     : the decision model re-reads ONLY the explanation (option names masked) as its state;
                 `faithfulness` = P(chosen | masked explanation alone), i.e. whether the explanation's evidence carries
                 the decision (simulatability, no teacher). With
                 n_samples > 1 the most faithful sample is returned; below `min_faithfulness` -> explanation None.
"""
from __future__ import annotations

import copy
import json
import re

import torch

from .batching import Question, state_texts
from .formatting import state_text


def _records(state):
    """[(path, removed_state, record_text)]: every top-level member/item, and members of large nested containers."""
    if isinstance(state, str):
        lines = state.strip().splitlines()
        return [((i,), "\n".join(lines[:i] + lines[i + 1:]), lines[i]) for i in range(len(lines)) if lines[i].strip()]
    out = []

    def rec(node, path, depth):
        items = list(node.items()) if isinstance(node, dict) else list(enumerate(node))
        for k, v in items:
            s = copy.deepcopy(state)
            parent = s
            for p in path:
                parent = parent[p]
            del parent[k]
            txt = json.dumps({k: v} if isinstance(node, dict) else v, ensure_ascii=False, separators=(",", ": "))
            out.append((path + (k,), s, txt.strip("{}") if isinstance(node, dict) else txt))
            if depth == 0 and isinstance(v, (dict, list)) and len(v) > 1:
                rec(v, path + (k,), depth + 1)
    if isinstance(state, (dict, list)):
        rec(state, (), 0)
    return out


def mask_options(text: str, names) -> str:
    """Hide every option name (and its spaced / hyphenated variants) so the faithfulness check measures the
    explanation's evidence, not a restated answer."""
    for n in sorted(names, key=len, reverse=True):
        for v in {n, n.replace("_", " "), n.replace("_", "-")}:
            text = re.sub(r"(?<!\w)" + re.escape(v) + r"(?!\w)", "[option]", text, flags=re.IGNORECASE)
    return text


class Explainer:
    def __init__(self, decider):
        self.dec = decider
        self.m = decider.model
        self.bb = self.m.backbone

    # ------------------------------------------------------------------ decision probabilities
    @torch.no_grad()
    def probs(self, states: list, q: Question) -> torch.Tensor:
        """P over q's options for each state (one batched state pass + rows), renormalised over real options."""
        mem = self.m.encode_states(state_texts(states))
        qs = [Question(q.prompt, q.options, q.type, state_idx=i) for i in range(len(states))]
        _, out = self.m.run(qs, mem)
        K = len(q.options)
        return torch.softmax(out.logits[:, :K].float(), -1)

    def evidence(self, state, q: Question, k: int = 3, max_records: int = 32):
        recs = _records(state)[:max_records]
        if not recs:
            return [], None
        P = self.probs([state] + [r[1] for r in recs], q)
        c = int(P[0].argmax())
        drop = (P[0, c] - P[1:, c]).tolist()
        text = state_text(state)
        top = sorted(range(len(recs)), key=lambda i: -drop[i])[:k]
        ev = []
        for i in top:
            if drop[i] <= 0:
                continue
            start = text.find(recs[i][2])
            ev.append({"text": recs[i][2], "path": list(recs[i][0]), "weight": drop[i],
                       "start": start, "end": start + len(recs[i][2]) if start >= 0 else -1})
        return ev, P[0]

    # ------------------------------------------------------------------ generation
    @torch.no_grad()
    def generate(self, prompt: str, max_new: int = 80, temperature: float = 0.0, n: int = 1, seed: int = 0,
                 adapters: bool = False) -> list[str]:
        """n continuations of `prompt` (batched), plain backbone by default (decision adapters off)."""
        bb, dev = self.bb, self.bb.device
        E = self.m.__dict__.get("_E")
        if E is None:
            E = bb.lm.embed_tokens.weight.detach().to(torch.bfloat16)
            self.m.__dict__["_E"] = E
        ids = torch.tensor([bb.tokenize([prompt])[0]] * n, device=dev)
        stop = {bb.tok.eos_token_id, *bb.tok.convert_tokens_to_ids(["<|im_end|>", "<|endoftext|>"])}
        g = torch.Generator(device=dev).manual_seed(seed)
        vera = getattr(self.m, "vera", None)
        prev = vera.active if vera is not None else None
        if vera is not None:
            vera.active = adapters
        try:
            h, cache = bb(ids, torch.ones_like(ids, dtype=torch.bool), ("final",), use_cache=True)
            out = torch.empty(n, 0, dtype=torch.long, device=dev)
            done = torch.zeros(n, dtype=torch.bool, device=dev)
            for _ in range(max_new):
                logits = (h[:, -1].to(torch.bfloat16) @ E.t()).float()
                if temperature > 0:
                    nxt = torch.multinomial(torch.softmax(logits / temperature, -1), 1, generator=g).squeeze(1)
                else:
                    nxt = logits.argmax(-1)
                nxt = torch.where(done, torch.full_like(nxt, bb.pad_id), nxt)
                out = torch.cat([out, nxt[:, None]], 1)
                done |= torch.isin(nxt, torch.tensor(sorted(stop - {None}), device=dev))
                if bool(done.all()):
                    break
                h, cache = bb(nxt[:, None], torch.ones(n, 1, dtype=torch.bool, device=dev), ("final",),
                              past_key_values=cache, use_cache=True)
        finally:
            if vera is not None:
                vera.active = prev
        texts = bb.tok.batch_decode(out.tolist(), skip_special_tokens=True)
        return [t.split("\n\n")[0].strip() for t in texts]

    # ------------------------------------------------------------------ end to end
    def explain(self, state, q: Question, names=None, n_samples: int = 1, temperature: float = 0.7,
                min_faithfulness: float = 0.0, k_evidence: int = 3) -> dict:
        names = names or q.options
        ev, p = self.evidence(state, q, k_evidence)
        if p is None:
            p = self.probs([state], q)[0]
        order = p.argsort(descending=True).tolist()
        c, r = order[0], order[1] if len(order) > 1 else order[0]
        opts = "; ".join(q.options)
        prompt = (state_text(state) + f"\nQuestion: {q.prompt}\nOptions: {opts}\n"
                  f"Decision: {names[c]} (probability {float(p[c]):.2f}); runner-up: {names[r]} ({float(p[r]):.2f}).\n")
        if ev:
            prompt += "Most influential parts of the state:\n" + "".join(f"- {e['text']}\n" for e in ev)
        prompt += (f"In one or two sentences, explain why the decision is {names[c]} rather than {names[r]}, "
                   f"citing the state.\nExplanation:")
        cands = self.generate(prompt, temperature=temperature if n_samples > 1 else 0.0, n=n_samples)
        cands = [x for x in cands if x] or [""]
        sim = self.probs([mask_options(x, names) for x in cands], q)[:, c].tolist() if cands[0] else [0.0]
        best = max(range(len(cands)), key=lambda i: sim[i])
        ok = sim[best] >= min_faithfulness and cands[best]
        return {"decision": names[c], "p": float(p[c]), "runner_up": names[r],
                "explanation": cands[best] if ok else None, "faithfulness": sim[best],
                "evidence": ev, "candidates": [{"text": t, "faithfulness": s} for t, s in zip(cands, sim)]}
